"""add diagnosis_completed and is_estimated flags

Revision ID: 123340a0545a
Revises: 8014747f7bb7
Create Date: 2026-04-26 19:47:14.924504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123340a0545a'
down_revision: Union[str, Sequence[str], None] = '8014747f7bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('diagnosis_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_skill_scores', sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skill_scores', 'is_estimated')
    op.drop_column('user_profiles', 'diagnosis_completed')
    # ### end Alembic commands ###
