"""add_tasks_per_day_to_enrollment

Revision ID: 4c5845f73ebe
Revises: a1b2c3d4e5f6
Create Date: 2026-05-03 22:08:37.208879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5845f73ebe'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_enrollments', sa.Column('tasks_per_day', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_enrollments', 'tasks_per_day')
    # ### end Alembic commands ###
