"""create progress_logs table

Revision ID: 8014747f7bb7
Revises: 1c8d3ac81389
Create Date: 2026-04-25 11:57:41.091538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8014747f7bb7'
down_revision: Union[str, Sequence[str], None] = '1c8d3ac81389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_logs_skill_id'), 'progress_logs', ['skill_id'], unique=False)
    op.create_index(op.f('ix_progress_logs_user_id'), 'progress_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_progress_logs_user_task_id'), 'progress_logs', ['user_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_logs_user_task_id'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_user_id'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_skill_id'), table_name='progress_logs')
    op.drop_table('progress_logs')
    # ### end Alembic commands ###
