"""add embedding fields to user_responses

Revision ID: cba14daab518
Revises: e6b355a12fa1
Create Date: 2026-05-01 22:10:57.231528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba14daab518'
down_revision: Union[str, Sequence[str], None] = 'e6b355a12fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('embedding_status', sa.Text(), server_default='pending', nullable=False))
    op.add_column('user_responses', sa.Column('pinecone_vector_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_user_responses_embedding_status'), 'user_responses', ['embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_responses_embedding_status'), table_name='user_responses')
    op.drop_column('user_responses', 'pinecone_vector_id')
    op.drop_column('user_responses', 'embedding_status')
    # ### end Alembic commands ###
