"""create user_profiles table

Revision ID: df1bc86e3382
Revises: bd0f19dcc205
Create Date: 2026-04-25 10:04:18.938991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1bc86e3382'
down_revision: Union[str, Sequence[str], None] = 'bd0f19dcc205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('self_assessed_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='self_assessed_level_enum'), nullable=False),
    sa.Column('daily_time_minutes', sa.Integer(), nullable=False),
    sa.Column('content_exposure', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='content_exposure_enum'), nullable=False),
    sa.Column('goal', sa.Enum('CASUAL', 'PROFESSIONAL', 'ACADEMIC', name='user_goal_enum'), nullable=False),
    sa.Column('interests', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
