"""Task module models — Task, TaskSkill junction, and related enums."""

from datetime import datetime

from enum import Enum

from sqlalchemy import DateTime, Enum as SQLAlchemyEnum, ForeignKey, Numeric, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.modules.skills.models import Skill

from app.core.database import Base
from app.core.mixins import IDMixin, TimestampMixin


# Enums
class TaskType(str, Enum):
    """Task activity type — drives which UI component renders."""
    READING = "reading"
    WRITING = "writing"
    SPEAKING = "speaking"
    LISTENING = "listening"


class TaskStatus(str, Enum):
    """Lifecycle of a task template."""
    DRAFT = "draft"
    ACTIVE = "active"
    ARCHIVED = "archived"

class UserTaskStatus(str, Enum):
    """Lifecycle of an assigned task for a user."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"


# Task — the master template
class Task(Base, IDMixin, TimestampMixin):
    """
    A task template — generated by the Task Agent or hand-authored.

    `content` holds the full structured task (passage, questions, answers)
    as JSON. Schema varies by task_type; validated in service layer.
    """

    __tablename__ = "tasks"

    title: Mapped[str] = mapped_column(String(200), nullable=False)
    task_type: Mapped[TaskType] = mapped_column(
        SQLAlchemyEnum(TaskType, name="task_type_enum"), nullable=False, index=True
    )
    difficulty: Mapped[int] = mapped_column(nullable=False, default=1)
    status: Mapped[TaskStatus] = mapped_column(
        SQLAlchemyEnum(TaskStatus, name="task_status_enum"),
        nullable=False, default=TaskStatus.ACTIVE, index=True,
    )
    # Full task body — passage, questions, answer keys. Shape depends on task_type.
    content: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Relationships
    task_skills: Mapped[list["TaskSkill"]] = relationship(
        back_populates="task", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Task(id={self.id}, type={self.task_type.value}, title={self.title!r})>"


# TaskSkill — junction table for Task ↔ Skill (M:N) with weights
class TaskSkill(Base, IDMixin):
    """
    Junction table linking a task to the skills it targets.

    The `weight` column stores how much this task contributes to each skill's
    score (e.g., grammar=0.7, vocab=0.3 for a grammar-focused writing task).
    """

    __tablename__ = "task_skills"

    task_id: Mapped[int] = mapped_column(
        ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True
    )
    skill_id: Mapped[int] = mapped_column(
        ForeignKey("skills.id", ondelete="CASCADE"), nullable=False, index=True
    )
    weight: Mapped[float] = mapped_column(
        Numeric(3, 2), nullable=False, default=1.0
    )

    # Relationships
    task: Mapped["Task"] = relationship(back_populates="task_skills")
    skill: Mapped["Skill"] = relationship()  # one-way; reach via TaskSkill.skill

    def __repr__(self) -> str:
        return f"<TaskSkill(task_id={self.task_id}, skill_id={self.skill_id}, weight={self.weight})>"

# UserTask — assignment record (User ↔ Task junction with state)
class UserTaskStatus(str, Enum):
    """Lifecycle of an assigned task for a user."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"


class UserTask(Base, IDMixin, TimestampMixin):
    """
    A specific task assigned to a specific user.

    Tracks status, when assigned, when completed.
    The user's response (if any) hangs off this row in UserResponse.
    """

    __tablename__ = "user_tasks"

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    task_id: Mapped[int] = mapped_column(
        ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True
    )
    status: Mapped[UserTaskStatus] = mapped_column(
        SQLAlchemyEnum(UserTaskStatus, name="user_task_status_enum"),
        nullable=False, default=UserTaskStatus.PENDING, index=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships 
    task: Mapped["Task"] = relationship()

    def __repr__(self) -> str:
        return (
            f"<UserTask(id={self.id}, user_id={self.user_id}, "
            f"task_id={self.task_id}, status={self.status.value})>"
        )