"""Data access for Task templates and UserTask assignments"""

from sqlalchemy.orm import Session, joinedload

from app.modules.tasks.models import (
    Task,
    TaskSkill,
    TaskStatus,
    UserTask,
    UserTaskStatus,
)

class TaskRepository:
    """Read access to the Task template table.
    
    Tasks are seeded. (or generated by the Task Agent) and rarely deleted.
    No update/delete methods here yet - services don't need them.
    """

    def __init__(self, db: Session) -> None:
        self.db = db 

    def get_by_id(self, task_id: int) -> Task | None:
        """Single task by primary key. Returns None  if not found"""
        return self.db.get(Task, task_id)
    
    def list_by_skill(
        self,
        skill_id: int,
        *,
        status: TaskStatus = TaskStatus.ACTIVE
    ) -> list[Task]:
        """Return all tasks targeting the given skill.
        
        Joins through TaskSkill (the M:N junction). By default only returns
        ACTIVE tasks - drafts and archived are hidden from callers.

        `joinedload` eagerly fetched each task's skill links in the same
        query, so callers can iterate `task.task_skills`
        """
        return (
            self.db.query(Task)
            .join(TaskSkill, TaskSkill.task_id == Task.id)
            .filter(
                TaskSkill.skill_id == skill_id,
                Task.status == status,
            )
            .options(joinedload(Task.task_skills))
            .order_by(Task.difficulty, Task.id)
            .all()
        )
    
class UserTaskRepository:
    """All DB access for UserTask (a task assigned to a specific user)"""

    def __init__(self, db: Session) -> None:
        self.db = db 

    # Reads 
    def get_by_id(self, user_task_id: int) -> UserTask | None:
        """Single assignment by primary key"""
        return self.db.get(UserTask, user_task_id)
    
    def list_for_user(
        self,
        user_id: int,
        *,
        status: UserTaskStatus | None = None,
    ) -> list[UserTask]:
        """Return all task assignments for a user, newest first.
        
        if `status` is given, filter to only that status (e.g. only PENDING). 
        Eager-loads the related Task so callers can read `ut.task.title`
        without a second query per row.
        """
        query = (
            self.db.query(UserTask)
            .filter(UserTask.user_id == user_id)
            .options(joinedload(UserTask.task))
            .order_by(UserTask.created_at.desc())
        )
        if status is not None:
            query = query.filter(UserTask.status == status)
        
        return query.all()
    
    # Writes
    def assign(self, *, user_id: int, task_id: int) -> UserTask:
        """Create a new assignment with default status (PENDING).
        
        Service decides when to commit - this method only flushes to get
        the new id populated.
        """
        assignment = UserTask(user_id=user_id, task_id=task_id)
        self.db.add(assignment)
        self.db.flush()
        return assignment
    
    def mark_completed(self, user_task: UserTask) -> UserTask:
        """Flip status to COMPLETED and stamp completed_at.
        
        Takes the ORM object directly (caller already has it from a read).
        Avoids a second SELECT just to fetch by id.
        """
        from datetime import datetime, timezone 
        
        user_task.status = UserTaskStatus.COMPLETED
        user_task.completed_at = datetime.now(timezone.utc)
        self.db.flush()
        return user_task 

    